### ISSUE TITLE
Player can't use elevator, flying mounts & mounts

### ISSUE THREAD

**Issue by d3athbl0w** [Lillecarl/mangos-tbc#11]
Player can't use elevator, flying mounts & mounts

¿Any fixs?

**Comment by d3athbl0w** [comment]
Wallclimb with elevator, flycheat in mounts

**Comment by d3athbl0w** [comment]
In the zepelín too :c

**Comment by Lillecarl** [comment]
I'll be looking into those :)

**Comment by Lillecarl** [comment]
Also please report one issue per issue. Otherwise it's very hard for me to keep track of things
