### ISSUE TITLE
Battleground chat with crossfactionBG & issues

### ISSUE THREAD

**Issue by d3athbl0w** [Lillecarl/mangos-tbc#16]
Team Can´t speak, any solution?

I also found an error activating warsong gulch 1v1 in battleground_template, the error is that once inside the battlefield a player comes out again the battle box as if he had scored bg again, if he gives enter he sends it to another BG ID

2 Issues, any solution? Thanks @Lillecarl For support.

**Comment by Lillecarl** [comment]
Which branch are you using? 😄

**Comment by d3athbl0w** [comment]
B16 merge with crossfaction_battlegrounds & cmangos branch check this branch based on your project, i like it <3 
I tried to implement eluna engine but I could not, fix merge problems but not compile.

Thanks @Lillecarl for make a good anticheat system & crossfactionbg.

**Comment by Lillecarl** [comment]
Could you try this on a clean https://github.com/Lillecarl/mangos-tbc/tree/crossfaction_battlegrounds checkout? I'll happily try and resolve it 😄 

Thanks for the kind words too!

**Comment by Lillecarl** [comment]
This is alot less broken now, fyi
