### ISSUE TITLE
Anticheat bug with fly mount

### ISSUE THREAD

**Issue by d3athbl0w** [Lillecarl/mangos-tbc#17]
the anticheat needs more fixes when it comes to flying mount, even every 3 seconds when flight returns to me down or 3 seconds ago, when I come down with the letter x too, is there a solution? 

https://ibb.co/igcUA6

**Comment by rayonpt** [comment]
I can confirm this too. It happens often when you ride a 310% mount on 280% it only stucks when you press letter X.

anyone have fix to this?

**Comment by Lillecarl** [comment]
I've completely missed this, i can reproduce and will look at it :)

**Comment by Lillecarl** [comment]
Please keep reporting issues, sorry for being slow on the resolution time. It must've drowned with other github notifications :)
