### ISSUE TITLE
Karazhan Chess Event

### ISSUE THREAD

**Issue by rayonpt** [Lillecarl/mangos-tbc#20]
Hello, I've tested Karazhan chess event and it needs a little bit more coding, we can start the event but the character runs to the top of the stairs and get out of chess event.

I know it's a hard issue to correct but would be nice to have this good would be a nice step to this core.

Thanks

**Comment by Lillecarl** [comment]
This should be reported to https://github.com/cmangos/issues I haven't changed anything related to that event (I only do issues here for the custom stuff in my fork :)

Please report it more thorough there and they should be able to check it out (Test with a clean cmangos-tbc and tbc-db too)

Thanks :)
