### ISSUE TITLE
Can't compile on MacOS High Sierra 

### ISSUE THREAD

**Issue by Lillecarl** [Lillecarl/mangos-tbc#23]
Apple is a shitshow

**Comment by Lillecarl** [comment]
Works without pch for some reason yet to be known

**Comment by Lillecarl** [comment]
I'm on Mojave now and it's still the same thing, w/o PCH works fine

**Comment by Lillecarl** [comment]
@cala

**Comment by cala** [comment]
Thanks @lillecarl. My last concern is about the native Mac clients not running under Mojave (they do run with High Sierra).

**Comment by Lillecarl** [comment]
@cala client runs on mojave, wouldn't bet higher than that though.

**Comment by Lillecarl** [comment]
@cala Have you checked this one out? https://www.codeweavers.com/about/blogs/jwhite/2019/12/10/celebrating-the-difficult-the-release-of-crossover-19
