### ISSUE TITLE
ItemGossip branch

### ISSUE THREAD

**Issue by hguy23** [Lillecarl/mangos-tbc#24]
Hey, i have used your code for itemgossip in cmangos. 

Script there: https://pastebin.com/jbt5N70a

Here is full code of item, but when i do .add of item server crashing, dunno why, because crashlog's are not generated for me. Any idea about that ? Thanks.

**Comment by hguy23** [comment]
#Update I have used debug, and it crashing there. http://prntscr.com/ky62lm

**Comment by Lillecarl** [comment]
So you added this commit onto normal cmangos? https://github.com/Lillecarl/mangos-tbc/commit/3f60fe38e7fe7e41b17e5e7f8a0428fabe7cc223

**Comment by hguy23** [comment]
Yes, now it's working. Just copy-paste fail. I just missed to re-copy `pGOUse(nullptr),`

**Comment by Lillecarl** [comment]
Sweet mate, good job 😁
