### ISSUE TITLE
Spell regulator crash

### ISSUE THREAD

**Issue by Lillecarl** [Lillecarl/mangos-tbc#29]
Apparently crashes if you add an id that doesn't exist.

**Comment by vhiperdev** [comment]
Confirmed, and tbm for existing IDs I was trying to put a spell of a Boss and not recognized in the table.

**Comment by Lillecarl** [comment]
Yeah do you have a crash log? I think it has to do with the loading of spell chains for classes, but I'm on my phone now so I can't verify this.

**Comment by Lillecarl** [comment]
Fixed crash in https://github.com/Lillecarl/mangos-tbc/commit/3c5dd63e0360eec6c82263e3b3eee773ecc67876

Now you should be able to modify any spell in the game :)
