### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by abennette32** [Lillecarl/mangos-tbc#3]
When compiling ScriptDev2, you get

    1>c:\mangos\mangos\src\game\WorldSession.h(31): fatal error C1083: Cannot open include file: 'WardenBase.h': No such file or directory

There is no WardenBase.h anywhere in the repo.

**Comment by Lillecarl** [comment]
I do not support SD2.

And only use mangosdVC120.sln

If problem persists please comment again! :)
