### ISSUE TITLE
Werid interaction with fly anti-cheat

### ISSUE THREAD

**Issue by BlessedPinkie** [Lillecarl/mangos-tbc#33]
As shown in the video it seems the anti-fly cheat seems to be causing the software to register new movement information onto other players. In shattrath this is amplfied by 100 so I untimatlely turned off the cheat in the main city. Turning off the anti-fly cheat function stops the issue occuring.

Going in and out of flight form while flying is a good way to reproduce the issue. Trying to identify the problem, not having much luck as i'm struggling to debug it.

https://youtu.be/KIDYfksq5W4

Aside from this if the code is given enough of a buffer to account for players with high latency for the most part the anti-cheat system works great. I really like it.

**Comment by BlessedPinkie** [comment]
https://github.com/cmangos/mangos-tbc/pull/309 <--- fix

**Comment by Lillecarl** [comment]
I kinda missed this one, good job mate!
