### ISSUE TITLE
Speed cheat 

### ISSUE THREAD

**Issue by kuramajssken001** [Lillecarl/mangos-tbc#4]
speed cheat fail
fly cheat fail 
@Lillecarl

**Comment by Lillecarl** [comment]
Yes indeed, they were never finished, needs more research

**Comment by Lillecarl** [comment]
@kuramajssken001 You could look at those cheatdetectors again and see if you get less issues.

Please note that this AC's task is to solve WoWEmuHacker, not every possible hack tool (yet).

**Comment by kuramajssken001** [comment]
I finished it two months ago.

**Comment by kuramajssken001** [comment]
Thank you

**Comment by Lillecarl** [comment]
Could you link whatever you're referring to? Sounds interesting.

**Comment by kuramajssken001** [comment]
Of course

**Comment by Lillecarl** [comment]
Might wanna take a look on how they're progressing, works rather ok now.
