### ISSUE TITLE
BRANCH B16 ADD CROSSFACTION BG & ELUNA

### ISSUE THREAD

**Issue by d3athbl0w** [Lillecarl/mangos-tbc#6]
Hi, lillecarl!

You have any guide how to add crossfaction BG & Eluna Engine to your Branch b16? Would be of much help to me, You have done a great job implementing the Anticheat! It's advice! :D

**Comment by Lillecarl** [comment]
Hi!

Sorry for not coming back to you, completely missed this.

It's probably easier to port the anticheat to your mangos, i made it affect the core as little as possible :)

If you're interested still i could try and help you with some pointers :)

**Comment by d3athbl0w** [comment]
@Lillecarl The anticheat is detecting with flying mounts, any solution?

**Comment by Lillecarl** [comment]
Are you using the latest version? And when does it happen, does it happen when flying regularly or when mounting and dismounting?

**Comment by d3athbl0w** [comment]
Regularly check my repo in: https://github.com/d3athbl0w/mangos-tbc inspirated in your branch xd

¿Can you add PlayerBots, CrossfactionBG & ElunaEngine to b16 (Actually) Branch? <3 Please T^T

**Comment by Lillecarl** [comment]
PlayerBots will come once CMaNGOS merges them into their master branch, Eluna will never ever be in my branch, though i'm gonna add a simple scripting system for custom scripts, which will be made completely with flexibility in mind =)

**Comment by Lillecarl** [comment]
@d3athbl0w https://github.com/Lillecarl/mangos-tbc/commit/72581429252e31c49e62c9a07ce030cabf74f840 This is the fix for flying mounts, didn't know flying mounts set the levitate moveflag.

EDIT: Please keep reporting issues you find with the AntiCheat, it'd be great for me to keep making it better :)

**Comment by d3athbl0w** [comment]
Thanks for the fix lillecarl, cheat engine for speed cheat is undetectable ,the trackeable people in WoW emu hack also, any fix¿?

**Comment by Lillecarl** [comment]
@d3athbl0w Not yet, but i assume i know why this happens.
https://github.com/Lillecarl/mangos-tbc/blob/b16/src/game/AntiCheat/AntiCheat.cpp#L245

See this function? It trusts the client reports the correct time between packets (This is intended).

What's next up is writing a "module" which checks that the client and server clock doesn't operate at different speeds, this will get Cheatengine as it essentially makes everything of the game move faster.

So it'll be ok in time :)

**Comment by Lillecarl** [comment]
https://github.com/Lillecarl/mangos-tbc/commit/9ec390e6ab6684395a6ef8474fd05a98581f41a1 Ill work more at this at some point, will probably put cheatengine hackers off.

Might also include a lazy detect on the speedhack module that uses servertime and a bigger fail tolerance (with current cheat (WoWEmu) you can only hack like 7.05 without detection).

**Comment by Lillecarl** [comment]
@d3athbl0w https://github.com/Lillecarl/mangos-tbc/commit/5ea3baa8a7d54029e81b598557e500d3417320f7 CheatEngine detection working, tested for a few minutes in singleplayer mode.

I'll be waiting for feedback :)
